@echo off
echo Starting Video Library App...
echo.
echo [1/2] Starting Vite dev server...
start /B cmd /c "npm run dev:vite"

echo [2/2] Waiting for Vite to start...
timeout /t 3 /nobreak > nul

echo Launching Electron app...
npm run dev:electron
